# @package _global_
model:
  _target_: remfx.models.FXClassifier
  lr: 1e-4
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  network:
    _target_: torchaudio.models.HDemucs
    sources: ["mixture"]
    audio_channels: 1
    nfft: 4096

