# @package _global_
model:
  _target_: remfx.models.FXClassifier
  lr: 3e-4
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  mixup: False
  network:
    _target_: remfx.classifier.Cnn14
    num_classes: ${num_classes}
    n_fft: 2048
    hop_length: 512
    n_mels: 64
    sample_rate: ${sample_rate}
    model_sample_rate: ${sample_rate}
    specaugment: False
  