# @package _global_
model: 
  _target_: remfx.models.FXClassifier
  lr: 1e-4
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  network:
    _target_: remfx.models.Cnn14
    num_classes: ${num_classes}
    n_fft: 2048
    hop_length: 512
    n_mel: 128
    sample_rate: ${sample_rate}

