# @package _global_
model:
  _target_: remfx.models.RemFX
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  network:
    _target_: remfx.models.DemucsModel
    sources: ["mixture"]
    audio_channels: 1
    nfft: 4096
    sample_rate: ${sample_rate}
    channels: 48

