# @package _global_
defaults:
  - override /model: demucs
  - override /effects: all
seed: 12345
sample_rate: 48000
chunk_size: 262144 # 5.5s
logs_dir: "./logs"

accelerator: "gpu"
log_audio: True
# Effects
num_kept_effects: [0,0] # [min, max]
num_removed_effects: [0,5] # [min, max]
shuffle_kept_effects: True
shuffle_removed_effects: True
num_classes: 5
effects_to_keep:
effects_to_remove:
  - distortion
  - compressor
  - reverb
  - chorus
  - delay
datamodule:
  train_batch_size: 16
  test_batch_size: 1
  num_workers: 8

dcunet:
  _target_: remfx.models.RemFX
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  network:
    _target_: remfx.models.DCUNetModel
    architecture: "Large-DCUNet-20"
    stft_kernel_size: 512
    fix_length_mode: "pad"
    sample_rate: ${sample_rate}
    num_bins: 1025

classifier:
  _target_: remfx.models.FXClassifier
  lr: 3e-4
  lr_weight_decay: 1e-3
  sample_rate: ${sample_rate}
  mixup: False
  network:
    _target_: remfx.classifier.Cnn14
    num_classes: ${num_classes}
    n_fft: 2048
    hop_length: 512
    n_mels: 128
    sample_rate: ${sample_rate}
    model_sample_rate: ${sample_rate}
    specaugment: True
classifier_ckpt: "ckpts/classifier.ckpt"

ckpts:
  RandomPedalboardDistortion:
    model: ${model}
    ckpt_path: "ckpts/demucs_distortion_aug.ckpt"
  RandomPedalboardCompressor:
    model: ${model}
    ckpt_path: "ckpts/demucs_compressor_aug.ckpt"
  RandomPedalboardReverb:
    model: ${dcunet}
    ckpt_path: "ckpts/dcunet_reverb_aug.ckpt"
  RandomPedalboardChorus:
    model: ${dcunet}
    ckpt_path: "ckpts/dcunet_chorus_aug.ckpt"
  RandomPedalboardDelay:
    model: ${dcunet}
    ckpt_path: "ckpts/dcunet_delay_aug.ckpt"

inference_effects_ordering:
  - "RandomPedalboardDistortion"
  - "RandomPedalboardCompressor"
  - "RandomPedalboardReverb"
  - "RandomPedalboardChorus"
  - "RandomPedalboardDelay"
num_bins: 1025
inference_effects_shuffle: False
inference_use_all_effect_models: False