# @package _global_
defaults:
  - override /model: umx
  - override /effects: all
seed: 12345
sample_rate: 48000
chunk_size: 262144 # 5.5s
logs_dir: "./logs"
render_files: True
render_root: "./data"
accelerator: null
log_audio: True
# Effects
num_kept_effects: [0,0] # [min, max]
num_removed_effects: [0,5] # [min, max]
shuffle_kept_effects: True
shuffle_removed_effects: False
num_classes: 5
effects_to_keep:
effects_to_remove:
  - compressor
  - reverb
  - chorus
  - delay
  - distortion
datamodule:
  batch_size: 16
  num_workers: 8